### ISSUE TITLE
Secret Redstone Block output state

### ISSUE THREAD

**Issue by Anuuviem** [Wyn-Price/SecretRooms#18] opened 2019-11-18 06:59 UTC
MC 1.14.4
Forge X.1.90

When a secret redstone block receives input signal, functions right, after signal is terminated, block does not shut off.

**Comment by Wyn-Price** [comment] 2019-11-18 07:42
What version of secret rooms is this? This sounds like a duplicate of #12

**Comment by Anuuviem** [comment] 2019-11-26 07:31
Sorry for the late reply: secretrooms-6.0.5

**Comment by Wyn-Price** [comment] 2021-07-02 10:34
1.12 is no longer supported

**Closed as completed by Wyn-Price** 2021-07-02 10:34 UTC
