### ISSUE TITLE
Breaking one way blocks in server crashed the client

### ISSUE THREAD

**Issue by Nebula240** [Wyn-Price/SecretRooms#59] opened 2021-09-17 04:57 UTC
[crash-2021-09-17_01.51.24-client.txt](https://github.com/Wyn-Price/SecretRooms/files/7182735/crash-2021-09-17_01.51.24-client.txt)
[crash-2021-09-17_01.56.15-client.txt](https://github.com/Wyn-Price/SecretRooms/files/7182736/crash-2021-09-17_01.56.15-client.txt)

As it's says, breaking those blocks crashes the client, closing the game.

**Comment by mdonohue** [comment] 2022-01-08 19:18
the first log is less clear, but the second one 01.56.16, shows the getPooled NPE error:

```
java.lang.NullPointerException: Unexpected error
	at com.wynprice.secretrooms.client.world.DelegateWorld.getPooled(DelegateWorld.java:32) ~[?:1.16.5-1.1.3] {re:classloading}
	at com.wynprice.secretrooms.client.world.DelegateWorld.lambda$createFunction$0(DelegateWorld.java:38) ~[?:1.16.5-1.1.3] {re:classloading}

```

**Comment by mdonohue** [comment] 2022-01-08 19:24
this looks like the earliest report of the getPooled NPE bug.     The others should be closed as a duplicate of this bug:
#60 
#63 
#67

**Closed as completed** 2022-01-08 19:33 UTC
